### PR TITLE
Meta: Add script for build+running Jakt programs

### PR DESCRIPTION
**Pull request by jedieaston**
I thought the two commands to get a program built all the way was
somewhat unwieldy, so I added a little bash script to do it.

Much like Serenity, it's in a meta folder off the root. If there's anything that's super wrong please let me know, my bash scripting is rustier than I'd like to admit.

### CODE REVIEW

File: meta/run.sh [hunk 1]
```diff
@@ -0,0 +1,56 @@
+#!/usr/bin/env bash
+
+print_help() {
+    NAME=$(basename "$ARG0")
+    cat <<EOF
+Usage: $NAME [arguments...] [SOURCEFILE]
```
Comment (kleinesfilmroellchen) [inline meta/run.sh:6]: Mind you that jakt might gain other arguments in the future. Just replace "SOURCEFILE" with "arguments to jakt" or something. Also see #213 .

**Review by kleinesfilmroellchen — CHANGES_REQUESTED** [review]

File: meta/run.sh (hunk 1 above)
Comment (jedieaston) [reply meta/run.sh]: Fixed.

**Review by kleinesfilmroellchen — APPROVED** [review]

File: meta/run.sh [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+$SCRIPT_DIR/../target/debug/jakt "$@"
+
+JAKT_EXIT=$?
+if [ $JAKT_EXIT != 0 ]; then
+    echo "Compilation failed :^("
+    exit $JAKT_EXIT
+fi
+
+clang++ -std=c++20 -Iruntime -Wno-user-defined-literals -o jakt.out output.cpp 
+./jakt.out
```
Comment (linusg) [inline meta/run.sh:56]: No trailing whitespace, but trailing newline please

**Review by linusg — CHANGES_REQUESTED** [review]
> I thought the two commands to get a program built all the way was
somewhat unwieldy, so I added a little bash script to do it.

...but forgot to document its existence anywhere?

Also, please not period at the end of commit titles.

File: meta/run.sh [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+
+$SCRIPT_DIR/../target/debug/jakt "$@"
+
+JAKT_EXIT=$?
+if [ $JAKT_EXIT != 0 ]; then
+    echo "Compilation failed :^("
+    exit $JAKT_EXIT
+fi
+
+clang++ -std=c++20 -Iruntime -Wno-user-defined-literals -o jakt.out output.cpp
```
Comment (ADKaster) [inline meta/run.sh:55]: I broke this in adcaeb5a459a1fc147437b4d934041ad965d4f9f , it now will be "$@".cpp or.. since that's all the arguments, it'll be $1.cpp ? $last-arg.cpp ? something like that.

Comment (mustafaquraish) [reply meta/run.sh:55]: For what it's worth, this is what I've been using in my bash script to run stuff:
```bash
filename=$(basename -- "$1")
filename="${filename%.*}.cpp"

clang++ ... $filename ...
```

File: meta/run.sh (hunk 2 above)
Comment (jedieaston) [reply meta/run.sh]: Fixed, along with adding a note about it to README.md. Sorry I completely spaced on documentation, I wasn't 100% awake when I was doing this :)

File: meta/run.sh (hunk 3 above)
Comment (jedieaston) [reply meta/run.sh]: I used a modification of that snippet to find the filename, thanks @mustafaquraish! The way I have it if multiple Jakt files are passed to the compiler we will try to tell clang to use the last one passed.

**Comment by mustafaquraish** [comment]
Since #299 has been merged, I think we can leverage that functionality instead of also mirroring it in this shell script

**Comment by awesomekling** [comment]
> Since #299 has been merged, I think we can leverage that functionality instead of also mirroring it in this shell script

Agreed.
